# Configuration for generating synthetic sequence data
storage :
  # Output file path for generated sequences
  path: ../simple-llm-data/sequences.txt
  # transformed data
  transformed_path: ../simple-llm-data/transformed_sequences.txt
  # Delimiter between columns in output file
  column_delimiter: " "
  # Delimiter between rows in output file
  row_delimiter: "\n"
  # Replace or append the retrieved numbers
  replace_or_append: "replace" # "replace" or "append"

data_generator:
  sequence_type : "sum" # "sum" 


sum:
  # Minimum value for number in initial sequence
  min_value: 0
  # Maximum value for number in initial sequence
  max_value: 9999 #99999
  # Percentage of numbers to retrieve
  retrieve_percent: 0.1 # 0.5
  # max length x  & y
  max_length: null





